---
- hosts: servers
  gather_facts: no

  tasks: 
    - name:   installing httpd
      yum:    pkg=httpd state=installed
      become: true

    - name: start HTTPD service
      service: name=httpd state=started
      become: true
      register: httpd_output

    - name: printing HTTPD O/P
      debug: var=httpd_output

    - name: printing status
      debug: msg="My Automation is Successful"
      when: httpd_output is succeeded
