---
- hosts: servers 
  # become root (using sudo, by default)
  become: yes
  tasks:

    - name: Install Wget
      yum: pkg=wget state=present
      register: install_wget
      ignore_errors: yes
    - name: Download EPEL RPM
      get_url: url=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm dest=/tmp mode=0700
      register: download_epel
      when: install_wget is succeeded
      ignore_errors: yes
    - name: Install EPEL Repo
      shell: rpm -Uvh /tmp/epel-release-latest-7.noarch.rpm
      register: install_epel_repo
      when: download_epel is succeeded 
      ignore_errors: yes   
    - name: Install nginx.
      # the 'package' module is new, and abstracts things like 'yum' 'apt,' and 'pkg' away
      package: name={{ item }} state=present
      # iterates over items
      with_items:
        - nginx
        # superfluous, should be split into a separate playbook
       # - vim
        - nano
        - sshguard
        - curl
      ignore_errors: yes
    - name: Create website directory
      file: path=/var/www/mywebsite state=directory mode=0755

    - name: Copy nginx config files (main config and vhost config)
      # copy FROM ansible controller to target machine (fetch is the opposite)
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      # more complex iteration: each item now has src: and dest: attributes
      with_items:
        - src: "config/nginx.conf"
          dest: "/etc/nginx/nginx.conf"
        - src: "config/mywebsite.conf"
          dest: "/etc/nginx/conf.d/mywebsite.conf"
        - src: "config/index.html"
          dest: "/var/www/mywebsite/index.html"

    - name: Check if default nginx vhost still exists
      stat: path=/etc/nginx/con.d/default.conf
      register: default_conf

    - name: Remove default nginx vhost configuration
      file: path=/etc/nginx/con.d/default.conf state=absent
      when: default_conf.stat.exists

    - name: Start nginx at boot + make sure it's running right now.
      service: name=nginx state=restarted enabled=yes

